### ISSUE TITLE
More missing solutions?

### ISSUE THREAD

**Issue by arpruss** [midjji/pnp#5]
Despite your recent fix of the solver, I am still having trouble with real-world data. 

It could be a bug in my [C port](https://github.com/arpruss/lambdatwist_p3p_c) of your code, which is what I am using for testing as I am not very good with C++. My apologies if it's my fault. 

Here is the data that doesn't work for me:

  Vector3 x1 = {0.355263, -0.0518519, 0};
  Vector3 x2 = {0.644737, -0.0518519, 0};
  Vector3 x3 = {0.710526, 1.02963, 0};
  Vector3 x4 = {0.289474, 1.02963, 0};

  Vector2 y1 = {-0.06901041666666667, -0.3138020833333333};
  Vector2 y2 = {0.11328125, -0.31640625};
  Vector2 y3 = {0.15364583333333334, 0.07682291666666667};
  Vector2 y4 = {-0.11197916666666667, 0.0703125};

I feed the first three vectors from each quad to p3p, and then apply the solutions to x4 to see how far off from y4 we are. 

I get two solutions, and both of them are really far off. One estimates y4 at -0.0202205, 0.0671298, and the other estimates it at out -0.472997, 0.0518886. I checked that y1 through y3 are correct.

The data comes from a Wii remote pointed at a quadrilateral of LEDs (mounted around a TV, for a retro gaming lightgun), with some non-uniform rescaling of both inputs and outputs. 

I have no difficulty processing this data using this homography p4p algorithm: https://web.archive.org/web/20190503154012/http://www.corrmap.com/features/homography_transformation.php

**Comment by midjji** [comment]
Its not obvious to me that the observations you would get from such a configuration would be pinhole normalized which is a requirement of p3p and p4p.   To be clear, the error you found truly was a very rare case, it dropped the failure rate of my system from 10^-5 to 10^-6 in simulation of real data. Meaning when the data does not have some super specific symmetry, or is degenerate(which the points above arent), its extremely unlikely to be another special case. I have used this code for projects like that near daily for years on real data without ever finding the problem you found. 

I will verify this to be sure tomorrow, but I find it quite unlikely. However, if its a question of a bad intrinsics calibration, instead of no intrinsics calibration(See https://docs.opencv.org/3.4/dc/dbb/tutorial_py_calibration.html) you can try to put the four points into the pnp function instead, ideally adding a few more points. 

A general homography relates any four points on a plane, to any four points on another plane, so its guaranteed to work. But homography estimation is not perspective from four points, as it only supports planes, and is insufficient on its own to give you the relative pose. 

I recommend learning a bit of C++, it does not have to be complicated. Just use the basics like structs with member functions for which matrix is just about a perfect example, and ofstream instead of file letting the destructors automate resource management, meaning no need to manually close ever again. C code tends to become a readability and maintenance nightmare.

**Comment by arpruss** [comment]
Thanks! It is actually a case of no intrinsics. No need for you to investigate further.

For my use case, I don't need the pose. I have four IR LEDs around the screen, and need to figure out where on the screen the center of the camera - or, better, the sights above the camera - is pointing. Planar homography without any camera correction gives me all the precision I normally need, but sometimes the camera doesn't pick up one of the LEDs, in which case I have the code drop to p3p and guess which solution is right based on past data. This works surprisingly well.

When I was learning numerical programming three decades ago, C++ was too slow for serious numeric stuff, and so I used Fortran and C, and didn't bother learning C++. I've picked up enough since to make Arduino libraries. :-)

**Comment by midjji** [comment]
Heh,
And i thought i was an old timer still using C++... Todays compilers are
good enough that trying to help them is almost universally futile. There is
no performance advantage to c over c++, and in most cases c suffers
performancewise as the user will make bad interfaces and worse algorithms
due to not beeing able to see or implement the more advanced ones in c,
were c++ would make it trivial. Not to mention the library of c stuff every
programmer builds up and then half remakes, half copies for each project,
instead of using the bigger better standard library, or the massively
increased number of bugs and longer implementation times. Its well worth
making the change.

**Comment by midjji** [comment]
As far as I can tell the missing pinhole normalization was the problem.

**Comment by arpruss** [comment]
Yup, thanks for the help.
BTW, my C version is about 20% faster than the C++ version, perhaps because of not having overhead of the vector library (I just use array).

**Comment by midjji** [comment]
Yeah the benchmark version does not use heap alloc.
