### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by bfialkoff** [midjji/pnp#7]
Hi, 

Any chance you can provide some directions for building with python bindings?
I tried running (from inside a build directory)
`cmake ../ -DPYTHON_EXECUTABLE="path/to/python_executable"`.
I changed:
`option(WITH_PYBIND11 "with pybind11 bindings" OFF)` to this `option(WITH_PYBIND11 "with pybind11 bindings" ON)`
then ran `make && make install`. 
It failed with the following error `make: *** No rule to make target `install'.  Stop.`
I'd appreciate some pointers.

**Comment by midjji** [comment]
There is no installer configured,
Its easier to just use add_subdirectory in cmake.

For python im less sure. I think there is an example uou can use.

**Comment by bfialkoff** [comment]
I think my issue was primarily about resolving dependencies and try to build on arm. successfully built on linux x86_64, clsoing for now, hopefully ill make a PR later if youre interested.

**Comment by midjji** [comment]
Cool, I Havent looked at the p3p asm on arm, but the ceres portion
dominates anyways as long as your inlier ratio is above 10-15% anyways.

**Comment by bfialkoff** [comment]
Unfortunately my initial results look awful! In particular the translation
component is 3 or 4 orders of magnitude too large.

Do you have any idea what could be going wrong? I am making my normalized
coordinated my taking the inverse of KE  (intrinsic times extrinsic) times
the  of the undistorted pixel values and then normalizing by the homogenous
coordinate.

**Comment by midjji** [comment]
Pnp estimates the pose of a camera in the coordinate system of the 3d
points used. So if you have a pinhole camera observations y_n of 3d points
x_world, the pnp(yn, x_world) will give you the pose which matches the
observation model

x_c = x_camera = P_cw x_w

y_n = project(x_c0/x_c2, x_c1/x_c2)

If you have a camera with known camera intrinsics you need to compute the
corresponding pinhole normalized coordinates,

e.g. if you have the linear intrinsics K and the observation model y_rowcol
(pixels)= K project(Pcw x_world)

then compute yn = inv(K)y_rowcol

if the lens model is non-linear you will need to do invert the lens model,
at least for where you are interested in it. The best way to do this is to
estimate a regularized 2d spline surface over the image and use as a lookup
table.

If the camera is offset from the vehicle, i.e. you are using the
observation model y_rowcol (pixels)= distort(K, th, project(Pcv Pvw
x_world)) and the extrinsics (Pcv =P_camera_vehicle) are known, then
normalize the coordinates as before and compute pnp Pcw, followed by
finding the pose of vehicle in world as Pvw = inv(Pcv)Pcw

**Comment by midjji** [comment]
So yeah, the intrinsics should not be used that way, and definitely not in
essential matrix form

**Comment by bfialkoff** [comment]
Thanks for the clarification, it helped me to clear everything up. Almost. Would it be alright with you if I asked another question? What would be the appropriate forum for that?

**Comment by midjji** [comment]
Feel free to ask, if the question would take too long to answer, ... I will
refer you to one of the computer vision experts/phds of my consulting
company.

**Comment by bfialkoff** [comment]
I have two calibrated camera (intrinsics and extrinsics) and a known 3d object. The cameras are connected and they move together. In the new position I have a set of image points in the new position that correspond to known object points. So basically the goal is to find the RT that moved the cameras that satisfies the new correspondences. This can be viewed as recalibrating the extrinsics. 

I am attempting to combine the data from the two cameras into a pnp call. Since I know that the cameras move together. 
I am acutally not sure this is possible without digging into the Cpp code, but I feel like it should be. Below is my attempt.
Can you think of anything that can take me to the next step?
 
Let `@` denote matrix multiplication then the following holds for two cameras` i=1,2
`
```
inv(K_1) @ y_1 = E_1 @ RT @ X_1_w
inv(K_2) @ y_2 = E_2 @ RT @ X_2_w
```

In order to combine the two equations I transformed X_1 and X_2 to their respencive camera frames as follows

`E_1 @ X_1 and E_2 @ X_2. 
`The formulation now becomes

```
inv(K_1) @ Y_1 = R'T' @ X_1_c1
inv(K_2) @ Y_2 = R'T' @ X_2_c2
```

so` RT = inv(E_1) @ R'T' @ E_1 = inv(E_2) @ R'T' @ E_2`

**Comment by midjji** [comment]
You are in the last case I described above.
If you want to use the unmodified cpp code to estimate the vehicle pose,
and there are at least 4 observations in one camera. Run pnp on only those
from one camera. If all are inliers it will work.
You may then want to perform a second non-linear refinement over the
inliers in both cameras.
This is not possible using the simplified api, but studying the code for
offset_reprojection error in midjji/mlib will show you how to modify the
cpp to do so.

Without enough points in one camera the p3p type solver which is the basis
for this pnp cannot be used.
There are solvers for this case as well, but they have significant
downsides, and the better option in practice is to add another few markers
and observations.

Note that the last line of your explanation does not follow from the
preceding ones. I recommend Hartleys book on multiple view geometry, the
classics never go out of date.

**Comment by bfialkoff** [comment]
> This is not possible using the simplified api, but studying the code for offset_reprojection error in midjji/mlib will show you how to modify the cpp to do so.

I will do my best. Can you direct me to the correct script? I dont see any file called (or containing) offset_reprojection in either  midjji/mlib or  midjji/pnp.

Thanks for your help its been super helpful!

**Comment by midjji** [comment]
ah turns out that has been replaced by something with a higher abstraction
level,  I use the ones in ceres?util,
the loss is basically:

struct Intrinsics {
Posed Pcv; // transform to vehicle coordinates
Matrix3d K;// or some operator for the lens // y row, col,
template<class T> Vector2<T> operator(const Vector3<T>& x_v){        return
(Matrix3<T>(K)*(Pose<T>(Pcv)*x_v)).dehom);}
};

class ReprojectionCost
{
public:
    Intrinsics intrinsics;
    Vector2d y; // (row,col)
    static constexpr int resids=2;
    ReprojectionCost(Intrinsics intrinsics, Vector2d
y):intrinsics(intrinsics),y(y){}
    template <typename T>
    bool operator()(const T* const Pvw_,
                    T* residuals) const
    {
        Vector2<T> yp=intrinsics(Pvw*Vector<T,StateSize>::copy_from(Xw_));
        for(int i=0;i<resids;++i)
            residuals[i]=T(y[i])  - yp[i];
        return true;
    }
}; // prefilter the points to the ones infront of the observing camera. and
use a loss function suitable for the noise.

**Comment by bfialkoff** [comment]
I did it :) 
I think this is a great testament to your code's clarity.
Thanks for the help

**Comment by midjji** [comment]
Thats great, :)

**Comment by bfialkoff** [comment]
I'm asking here because I dont know of any other forum to ask you this.
Is there any fundamental reason why this has to work with normalized coordinates?
I was thinking of changing it to work with absolute coordinates. 
I ask because I have a bundle adjustment type algorithm in use somewhere and I just adapted it to also work with normalized coordinates thinking that it might help convergence time or something and instead I found that it failed to converge. Also, my adapted Lambdatwist fails to converge and I wonder if it has to do with the normalization.

**Comment by midjji** [comment]
It uses normalized coordinates, because if the coordinates are pinhole
normalized, there are 6 degrees of freedom, those of the rotation and
translation. Otherwise there are more than 6 degrees of freedom. how many
depends on the camera model. It is most likely literally unobservable i.e.
impossible.

Assuming your camera is correctly calibrated its trivial to normalize the
coordinates. As in one matrix multiplication. Deriving a pxp variant for a
custom camera model is the work of 6 months for a phd, dont try that, its a
bad idea.
Generate synthetic data and test your framework. This will likely show a
bunch of errors and misconceptions. Then generate some manual
correspondences between real images and known 3D. Then try to normalize
those and verify it works. That will also likely show a pile of
misconceptions and errors.
Then recalibrate the camera now that you know what you are doing to some
extent. It will have been crappily calibrated, because calibrating cameras
is hard, and no one, including very highly paid engineers get it right
unless they use the results themselves.
There are many reasons to use image coordinates instead of pinhole
normalized coordinates in bundleadjustment, but interpretability and ease
of refining the camera model is formost. This is not a recommended practice
for the pnp however.

I recommend that you read hartleys multiple view geometry, and study the
ceres-solver examples.

**Comment by midjji** [comment]
Remember that sfm is computer graphics backwards, so unless you find it
trivial to build you own minimal renderer for e.g. at least colored points
from scratch you should start with that.
Make the point colors unique, and you can use them for correspondences.
The full chain from 3d point x to 2d observation should look something like

Y= proj(KPX) for non trivial K,P,X at a minimum . But adding  in some nl
optics is good too.


Lambdatwist is a low level sfm component, if you want something higher
level consider colmap.
